# Generated by Django 3.0.7 on 2020-06-05 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('order_date', models.DateField()),
                ('total_cost', models.IntegerField()),
                ('sts', models.DateTimeField(auto_now_add=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OrderDetail',
                'verbose_name_plural': 'OrderDetails',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('delivery_slot_pref', models.CharField(choices=[('7:00 - 7:30 AM', '7:00 - 7:30 AM'), ('7:30 - 8:00 AM', '7:30 - 8:00 AM'), ('8:00 - 8:30 AM', '8:00 - 8:30 AM'), ('8:30 - 9:00 AM', '8:30 - 9:00 AM'), ('9:00 - 9:30 AM', '9:00 - 9:30 AM'), ('9:30 - 10:00 AM', '9:30 - 10:00 AM')], default='7:00 - 7:30 AM', max_length=250)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('item_cost', models.IntegerField()),
                ('menu_items_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='core.OrderDetails')),
                ('order_details_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.OrderDetails')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
            },
        ),
    ]
