# Generated by Django 3.0.7 on 2020-06-05 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0001_initial'),
        ('core', '0002_orderdetails_orderitems_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='menu_items_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='foodmenu.FoodItems'),
        ),
    ]
