# Generated by Django 3.0.7 on 2020-06-05 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0001_initial'),
        ('core', '0003_auto_20200605_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='menu_items_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_in_order', to='foodmenu.FoodItems'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order_details_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='core.OrderDetails'),
        ),
        migrations.CreateModel(
            name='UserNotifToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserNotifToken',
                'verbose_name_plural': 'UserNotifTokens',
            },
        ),
    ]
