# Generated by Django 3.0.7 on 2020-06-04 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='menuitems')),
                ('is_veg', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
            },
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('pincode', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='MenuForTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fooditem_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='foodmenu.FoodItems')),
            ],
            options={
                'verbose_name': 'Menu For The Day',
                'verbose_name_plural': 'Menu For The Day',
            },
        ),
        migrations.AddField(
            model_name='fooditems',
            name='restaurant_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='foodmenu.Restaurants'),
        ),
    ]
